services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    ports:
      - "4306:3306"
    
    environment:
      MYSQL_DATABASE: url-db
      MYSQL_ROOT_PASSWORD: root
    
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: