services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: url-db
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    container_name: api_container
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/url-db
    depends_on:
      mysql:
        condition: service_healthy
    command: sh -c "npx prisma migrate dev && npm run start:prod"
    restart: on-failure
    
volumes:
  mysql_data: